# Generated by Django 5.1.1 on 2024-10-26 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_hiddencomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HiddenComment',
        ),
    ]
